name: Build Development Preview

on:
  push:
    branches:
      - dev

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: preview
  # build_ios:
  #   type: build
  #   params:
  #     platform: ios
